--BORRADO POBLACION - REINICIAR SECUENCIAS
DELETE FROM TIPOSUSUARIOS;
ALTER SEQUENCE "IDTIPOSUSUARIOS" RESTART;

DELETE FROM USUARIOS;

DELETE FROM TIPOSHABITACION;
ALTER SEQUENCE "IDTIPOSHABITACION" RESTART;

DELETE FROM ELEMENTOSDOTACION;
ALTER SEQUENCE "IDELEMENTOSDOTACION" RESTART;

DELETE FROM HABITACIONES;
ALTER SEQUENCE "IDHABITACIONES" RESTART;

DELETE FROM SERVICIOS;
ALTER SEQUENCE "IDSERVICIOS" RESTART;

DELETE FROM PISCINAS;
DELETE FROM GIMNASIOS;

DELETE FROM MAQUINASGIMNASIO;
ALTER SEQUENCE "IDMAQUINASGIMNASIO" RESTART;

DELETE FROM INTERNETS;
DELETE FROM BARES;
DELETE FROM ESTABLECIMIENTOSCOMERCIO;
DELETE FROM RESTAURANTES;

DELETE FROM PRODUCTOS;
ALTER SEQUENCE "IDPRODUCTOS" RESTART;

DELETE FROM SPAS;

DELETE FROM SERVICIOSSPA;
ALTER SEQUENCE "IDSERVICIOSSPA" RESTART;

DELETE FROM SERVICIOSLAVANDERIA;
DELETE FROM SALONESREUNION;
DELETE FROM SALONESCONFERENCIA;

DELETE FROM PLANESCONSUMO;
ALTER SEQUENCE "IDPLANESCONSUMO" RESTART;

--BORRADO ASOCIACIONES
DELETE FROM ELEMENTOSHABITACION;
DELETE FROM SERVICIOSPLANES;
DELETE FROM TIENEN;
DELETE FROM MENUSBARES;
DELETE FROM MENUSESTABLECIMIENTOS;
DELETE FROM MENUSRESTAURANTES;
DELETE FROM SPASSERVICIOSSPA;

--BORRADO TABLAS RESTANTES
DELETE FROM RESERVAS;
ALTER SEQUENCE "IDRESERVAS" RESTART;

DELETE FROM RESERVASHABITACIONES;

DELETE FROM CONSUMOS;
ALTER SEQUENCE "IDCONSUMOS" RESTART;

DELETE FROM RESERVASSPA;
ALTER SEQUENCE "IDRESERVASSPA" RESTART;

DELETE FROM SERVICIOSSPARESERVASSPA;

DELETE FROM PRESTAMOS;
ALTER SEQUENCE "IDPRESTAMOS" RESTART;

DELETE FROM RESERVASSALONREUNION;
ALTER SEQUENCE "IDRESERVASSALONREUNION" RESTART;

DELETE FROM RESERVASSALONCONFERENCIA;
ALTER SEQUENCE "IDRESERVASSALONCONFERENCIA" RESTART;

--BORRADO DE TODAS LAS TABLAS
--Tablas Poblacion
DROP TABLE "TIPOSUSUARIOS" CASCADE CONSTRAINTS;
DROP TABLE "USUARIOS" CASCADE CONSTRAINTS;
DROP TABLE "TIPOSHABITACION" CASCADE CONSTRAINTS;
DROP TABLE "ELEMENTOSDOTACION" CASCADE CONSTRAINTS;
DROP TABLE "HABITACIONES" CASCADE CONSTRAINTS;
DROP TABLE "SERVICIOS" CASCADE CONSTRAINTS;
DROP TABLE "PISCINAS" CASCADE CONSTRAINTS;
DROP TABLE "GIMNASIOS" CASCADE CONSTRAINTS;
DROP TABLE "MAQUINASGIMNASIO" CASCADE CONSTRAINTS;
DROP TABLE "INTERNETS" CASCADE CONSTRAINTS;
DROP TABLE "BARES" CASCADE CONSTRAINTS;
DROP TABLE "ESTABLECIMIENTOSCOMERCIO" CASCADE CONSTRAINTS;
DROP TABLE "RESTAURANTES" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCTOS" CASCADE CONSTRAINTS;
DROP TABLE "SPAS" CASCADE CONSTRAINTS;
DROP TABLE "SERVICIOSSPA" CASCADE CONSTRAINTS;
DROP TABLE "SERVICIOSLAVANDERIA" CASCADE CONSTRAINTS;
DROP TABLE "SALONESREUNION" CASCADE CONSTRAINTS;
DROP TABLE "SALONESCONFERENCIA" CASCADE CONSTRAINTS;
DROP TABLE "PLANESCONSUMO" CASCADE CONSTRAINTS;

--Tablas Asociaciones
DROP TABLE "ELEMENTOSHABITACION" CASCADE CONSTRAINTS;
DROP TABLE "SERVICIOSPLANES" CASCADE CONSTRAINTS;
DROP TABLE "TIENEN" CASCADE CONSTRAINTS;
DROP TABLE "MENUSBARES" CASCADE CONSTRAINTS;
DROP TABLE "MENUSESTABLECIMIENTOS" CASCADE CONSTRAINTS;
DROP TABLE "MENUSRESTAURANTES" CASCADE CONSTRAINTS;
DROP TABLE "SPASSERVICIOSSPA" CASCADE CONSTRAINTS;

--Tablas restantes
DROP TABLE "RESERVAS" CASCADE CONSTRAINTS;
DROP TABLE "RESERVASHABITACIONES" CASCADE CONSTRAINTS;
DROP TABLE "CONSUMOS" CASCADE CONSTRAINTS;
DROP TABLE "RESERVASSPA" CASCADE CONSTRAINTS;
DROP TABLE "SERVICIOSSPARESERVASSPA" CASCADE CONSTRAINTS;
DROP TABLE "PRESTAMOS" CASCADE CONSTRAINTS;
DROP TABLE "RESERVASSALONREUNION" CASCADE CONSTRAINTS;
DROP TABLE "RESERVASSALONCONFERENCIA" CASCADE CONSTRAINTS;

--BORRADO SECUENCIAS
--Secuencias Poblacion
DROP SEQUENCE "IDTIPOSUSUARIOS";
DROP SEQUENCE "IDTIPOSHABITACION";
DROP SEQUENCE "IDELEMENTOSDOTACION";
DROP SEQUENCE "IDHABITACIONES";
DROP SEQUENCE "IDSERVICIOS";
DROP SEQUENCE "IDMAQUINASGIMNASIO";
DROP SEQUENCE "IDPRODUCTOS";
DROP SEQUENCE "IDSERVICIOSSPA";
DROP SEQUENCE "IDPLANESCONSUMO";

--Secuencias restantes
DROP SEQUENCE "IDRESERVAS";
DROP SEQUENCE "IDCONSUMOS";
DROP SEQUENCE "IDRESERVASSPA";
DROP SEQUENCE "IDPRESTAMOS";
DROP SEQUENCE "IDRESERVASSALONREUNION";
DROP SEQUENCE "IDRESERVASSALONCONFERENCIA";
