create sequence idElementosDotacion start with 1 increment by 1;
insert into elementosDotacion values (idElementosDotacion.nextval, 'TV');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Jacuzzi');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Minibar');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Cafetera');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Comedor');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Cocina');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Aire acondicionado');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Escritorio y silla');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Perchas en el armario');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Secador de pelo');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Reproductor de peliculas');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Consola de videojuegos');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Caja de seguridad');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Plancha');
insert into elementosDotacion values (idElementosDotacion.nextval, 'Telefono');
